### ISSUE TITLE
请问签名算法是什么了？

### ISSUE THREAD

**Issue by yhegago** [hegemony1/crawlProject#2]
看到你代码中，签名的生成是通过调用：https://api.anoyi.com/api/signature/ies/id  接口实现的。是否可以分享一下具体签名算法了？这个接口一直可用吗？

**Comment by HegemonyTao** [comment]
> 看到你代码中，签名的生成是通过调用：https://api.anoyi.com/api/signature/ies/id 接口实现的。是否可以分享一下具体签名算法了？这个接口一直可用吗？

这个是我看到一个别人做的网站上面的接口，并不是官方的接口。用的话，应该是没问题，就是不知道会不会被封ip什么的。

**Comment by yhegago** [comment]
哦，好的，多谢
